spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: accounting-service
          uri: lb://accounting-service
          predicates:
        - Path=/accounting/**
        - id: baggage-service
          uri: lb://baggage-service
          predicates:
        - Path=/baggage/**
        - id: boarding-service
          uri: lb://boarding-service
          predicates:
        - Path=/boarding/**
        - id: check-in-service
          uri: lb://check-in-service
          predicates:
        - Path=/check-in/**
        - id: data-references-service
          uri: lb://data-references-service
          predicates:
        - Path=/data-references/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
        - Path=/flight/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
        - Path=/inventory/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
        - Path=/payment/**
        - id: pricing-service
          uri: lb://pricing-service
          predicates:
        - Path=/pricing/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
        - Path=/reservation/**
        - id: search-service
          uri: lb://search-service
          predicates:
        - Path=/search/**
        - id: seating-service
          uri: lb://seating-service
          predicates:
        - Path=/seating/**


server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true